/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.math.BigInteger;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;

/**
 *
 * @author vigne
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    
    public ViewJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUniqueIdentifier = new javax.swing.JTextField();
        lblIdentity = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalrecordNumber = new javax.swing.JLabel();
        lblHealthplanNumber = new javax.swing.JLabel();
        lblBankaccountNumber = new javax.swing.JLabel();
        lblCertificatelicenseNumber = new javax.swing.JLabel();
        lblVehicleIdentifier = new javax.swing.JLabel();
        lblDeviceIdentifier = new javax.swing.JLabel();
        lblPersonalInfo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddressLine1 = new javax.swing.JLabel();
        lblAddressLine2 = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblDateofBirth = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddressLine1 = new javax.swing.JTextField();
        txtAddressLine2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtDateofBirth = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalrecordNumber = new javax.swing.JTextField();
        txtHealthplanNumber = new javax.swing.JTextField();
        txtBankaccountNumber = new javax.swing.JTextField();
        txtCertificatelicenseNumber = new javax.swing.JTextField();
        txtVehicleIdentifier = new javax.swing.JTextField();
        txtDeviceIdentifier = new javax.swing.JTextField();
        lblUniqueIdentifier = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        lblContactInfo = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        lblFaxNumber = new javax.swing.JLabel();
        lblBioinfo = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFaxNumber = new javax.swing.JTextField();
        txtEmailaddress = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtBiometricIdentifier = new javax.swing.JTextField();
        txtProfileImage = new javax.swing.JTextField();
        lblBiometricIdentifier1 = new javax.swing.JLabel();
        lblProfileImage1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPropicture = new javax.swing.JLabel();
        lblBiometricImage = new javax.swing.JLabel();

        txtUniqueIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIdentifierActionPerformed(evt);
            }
        });

        lblIdentity.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblIdentity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdentity.setText("Identity Info");

        lblSSN.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblSSN.setText("Social Security number:");

        lblMedicalrecordNumber.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblMedicalrecordNumber.setText("Medical Record Number:");

        lblHealthplanNumber.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblHealthplanNumber.setText("Health Plan Beneficiary Number:");

        lblBankaccountNumber.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblBankaccountNumber.setText("Bank Account Number:");

        lblCertificatelicenseNumber.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblCertificatelicenseNumber.setText("Certificate License Number:");

        lblVehicleIdentifier.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblVehicleIdentifier.setText("Vehicle Identifier:");

        lblDeviceIdentifier.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblDeviceIdentifier.setText("Device Identifier:");

        lblPersonalInfo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblPersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalInfo.setText("Personal Info");
        lblPersonalInfo.setToolTipText("");

        lblName.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblName.setText("Name:");

        lblAddressLine1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblAddressLine1.setText("Address Line1:");

        lblAddressLine2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblAddressLine2.setText("Address Line2:");

        lblZipcode.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblZipcode.setText("Zipcode:");

        lblDateofBirth.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblDateofBirth.setText("Date of Birth:");

        lblCity.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblState.setText("State:");

        lblIPAddress.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblIPAddress.setText("Internet Protocol Address:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine1ActionPerformed(evt);
            }
        });

        txtAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine2ActionPerformed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        txtDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateofBirthActionPerformed(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        txtMedicalrecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalrecordNumberActionPerformed(evt);
            }
        });

        txtHealthplanNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthplanNumberActionPerformed(evt);
            }
        });

        txtBankaccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankaccountNumberActionPerformed(evt);
            }
        });

        txtCertificatelicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificatelicenseNumberActionPerformed(evt);
            }
        });

        txtVehicleIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdentifierActionPerformed(evt);
            }
        });

        txtDeviceIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifierActionPerformed(evt);
            }
        });

        lblUniqueIdentifier.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblUniqueIdentifier.setText("Unique Identifier:");

        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });

        lblContactInfo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblContactInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContactInfo.setText("Contact Info");

        lblTelephoneNumber.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblTelephoneNumber.setText("Phone Number:");

        lblFaxNumber.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblFaxNumber.setText("Fax Number:");

        lblBioinfo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblBioinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBioinfo.setText("Biometric Info");

        lblEmailAddress.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblEmailAddress.setText("Email Address:");

        lblLinkedIn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblLinkedIn.setText("Linkedin:");

        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });

        txtFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumberActionPerformed(evt);
            }
        });

        txtEmailaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailaddressActionPerformed(evt);
            }
        });

        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        txtBiometricIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiometricIdentifierActionPerformed(evt);
            }
        });

        txtProfileImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfileImageActionPerformed(evt);
            }
        });

        lblBiometricIdentifier1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblBiometricIdentifier1.setText("Biometric Identifier:");

        lblProfileImage1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lblProfileImage1.setText("Profile Image:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblMedicalrecordNumber)
                                                            .addComponent(lblHealthplanNumber)
                                                            .addComponent(lblBankaccountNumber)
                                                            .addComponent(lblSSN))
                                                        .addGap(69, 69, 69)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtHealthplanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtMedicalrecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtBankaccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(538, 538, 538)
                                                        .addComponent(jLabel1))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblCertificatelicenseNumber)
                                                        .addGap(96, 96, 96)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtUniqueIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtCertificatelicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(338, 338, 338)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(txtBiometricIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(lblBiometricIdentifier1))))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblUniqueIdentifier)
                                                .addGap(913, 913, 913)))
                                        .addComponent(lblBiometricImage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblIPAddress)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDeviceIdentifier)
                                                .addComponent(lblVehicleIdentifier)))
                                        .addGap(1214, 1214, 1214)))
                                .addGap(276, 276, 276))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddressLine1)
                                    .addComponent(lblName))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDateofBirth)
                                    .addComponent(lblZipcode)
                                    .addComponent(lblState)
                                    .addComponent(lblCity)
                                    .addComponent(lblAddressLine2))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(lblIdentity))
                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(325, 325, 325)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblFaxNumber)
                                                    .addComponent(lblTelephoneNumber)
                                                    .addComponent(lblEmailAddress)
                                                    .addComponent(lblLinkedIn))
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmailaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblBioinfo)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblProfileImage1)
                                                            .addComponent(txtProfileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblPropicture, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5196, 5196, 5196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPersonalInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAddressLine1)
                                .addGap(18, 18, 18)))
                        .addComponent(lblAddressLine2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZipcode)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateofBirth)
                            .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(lblIdentity)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblContactInfo)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelephoneNumber)
                            .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFaxNumber)
                            .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailAddress)
                            .addComponent(txtEmailaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedIn)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addComponent(lblBioinfo)
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSSN)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblProfileImage1))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMedicalrecordNumber)
                                    .addComponent(txtMedicalrecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProfileImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHealthplanNumber)
                            .addComponent(txtHealthplanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankaccountNumber)
                            .addComponent(txtBankaccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCertificatelicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCertificatelicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPropicture, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicleIdentifier)
                            .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBiometricIdentifier1))
                        .addGap(18, 18, 18)
                        .addComponent(txtBiometricIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDeviceIdentifier)
                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblIPAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblUniqueIdentifier))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtUniqueIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblBiometricImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(280, 280, 280))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUniqueIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIdentifierActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine1ActionPerformed

    private void txtAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine2ActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void txtDateofBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateofBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateofBirthActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtMedicalrecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalrecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalrecordNumberActionPerformed

    private void txtHealthplanNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthplanNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthplanNumberActionPerformed

    private void txtBankaccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankaccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankaccountNumberActionPerformed

    private void txtCertificatelicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificatelicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificatelicenseNumberActionPerformed

    private void txtVehicleIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentifierActionPerformed

    private void txtDeviceIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifierActionPerformed

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumberActionPerformed

    private void txtEmailaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailaddressActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtBiometricIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiometricIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiometricIdentifierActionPerformed

    private void txtProfileImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfileImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfileImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddressLine1;
    private javax.swing.JLabel lblAddressLine2;
    private javax.swing.JLabel lblBankaccountNumber;
    private javax.swing.JLabel lblBioinfo;
    private javax.swing.JLabel lblBiometricIdentifier1;
    private javax.swing.JLabel lblBiometricImage;
    private javax.swing.JLabel lblCertificatelicenseNumber;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactInfo;
    private javax.swing.JLabel lblDateofBirth;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblHealthplanNumber;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblIdentity;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalrecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonalInfo;
    private javax.swing.JLabel lblProfileImage1;
    private javax.swing.JLabel lblPropicture;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblUniqueIdentifier;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JTextField txtBankaccountNumber;
    private javax.swing.JTextField txtBiometricIdentifier;
    private javax.swing.JTextField txtCertificatelicenseNumber;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDeviceIdentifier;
    private javax.swing.JTextField txtEmailaddress;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtHealthplanNumber;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalrecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProfileImage;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtUniqueIdentifier;
    private javax.swing.JTextField txtVehicleIdentifier;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
      
        txtName.setText(person.getName());
        txtAddressLine1.setText(person.getAddressLine1());
        txtAddressLine2.setText(person.getAddressLine2());
        txtCity.setText(person.getCity());
        txtState.setText(person.getState());
        txtZipCode.setText(person.getZipCode());
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");  
        String strDate = dateFormat.format(person.getDateofBirth());  
        txtDateofBirth.setText(strDate);          
        txtTelephoneNumber.setText(person.getTelephoneNumber());
        txtFaxNumber.setText(person.getFaxNumber().toString());       
        txtEmailaddress.setText(person.getEmailAddress());
        txtSSN.setText(person.getSocialsecurityNumber()); 
        txtMedicalrecordNumber.setText(person.getMedicalrecordNumber().toString()); 
        txtHealthplanNumber.setText(person.getHealthplanNumber().toString());       
        txtBankaccountNumber.setText(person.getBankaccountNumber());
        txtCertificatelicenseNumber.setText(person.getCertificatelicenseNumber());
        txtVehicleIdentifier.setText(person.getVehicleIdentifier());
        txtDeviceIdentifier.setText(person.getDeviceIdentifier());
        txtLinkedin.setText(person.getLinkedIn());
        txtIPAddress.setText(person.getIpAddress());
        txtUniqueIdentifier.setText(person.getUniqueIdentifier());
        Image getAbsolutePath = null;
        
        txtProfileImage.setText(person.getprofileImagepath());
        txtBiometricIdentifier.setText(person.getbiometricImagepath());
        
        ImageIcon profileIcon = new ImageIcon(person.getprofileImagepath());
        Image profileImage = profileIcon.getImage().getScaledInstance(200,50,Image.SCALE_REPLICATE);
        lblPropicture.setIcon(profileIcon);  
        
        ImageIcon biometricIcon = new ImageIcon(person.getbiometricImagepath());
        Image biometricImage = biometricIcon.getImage().getScaledInstance(200,50,Image.SCALE_REPLICATE);
        lblBiometricImage.setIcon(biometricIcon);  
       
     
       
    }
}
